# fly.production.toml app configuration file generated for tempowaiter on 2023-11-09T21:43:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "velmoro-backend"
primary_region = "waw"

[build]

[env]
  SPRING_DATASOURCE_PASSWORD = "compose-postgres"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/staging"
  SPRING_DATASOURCE_USERNAME = "postgres.ruexpbcygjdotksrkzbn"
  SPRING_MAIL_PASSWORD = 'kWy681@t'
  swap_size_mb = "512"

[deploy]
  strategy = "canary"
  max_unavailable = 1

[http_service]
  internal_port = 8080
  autoscale = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024